### ISSUE TITLE
Example Configuration Files

### ISSUE THREAD

**Issue by iamacarpet** [a1comms/GaeSupportLaravel#5]
We need some example app.yaml and .env files with documentation.

I don't think it'll be a good fit to auto-generate them from the artisan setup command if we want to easily be able to switch between Standard and Flexible, as that was more suitable as a one-time thing.

Create a samples folder with some examples?

**Comment by inbeacon** [comment]
yes this is really an omission as the gae:prepare command assumes there is something already there.

**Comment by iamacarpet** [comment]
This isn't so much of an issue with the php72 version, as things are a lot simpler.

There are example `app.yaml` files as part of the Cloud Build docs if required.
